USE [master]
GO
 
CREATE DATABASE [TestDB] ON  PRIMARY 
( NAME = N'TestDB', FILENAME = N'D:\TestDB\TestDB.mdf' , SIZE = 5048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1000KB ), 
 FILEGROUP [ConsTable] 
( NAME = N'ConsTable', FILENAME = N'D:\TestDB\TestDB.ndf' , SIZE = 5048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1000KB )
 LOG ON 
( NAME = N'TestDB_log', FILENAME = N'D:\TestDB\TestDB_log.ldf' , SIZE = 5048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TestDB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TestDB].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [TestDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TestDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TestDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TestDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TestDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [TestDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TestDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [TestDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TestDB] SET AUTO_UPDATE_STATISTICS OFF 
GO

ALTER DATABASE [TestDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TestDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TestDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TestDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TestDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TestDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TestDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TestDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TestDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TestDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TestDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TestDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TestDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TestDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TestDB] SET  READ_WRITE 
GO

ALTER DATABASE [TestDB] SET RECOVERY FULL 
GO

ALTER DATABASE [TestDB] SET  MULTI_USER 
GO

ALTER DATABASE [TestDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TestDB] SET DB_CHAINING OFF 
GO


